<?php

use Laminas\Escaper\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$data = $block->getData();

$handles = array_values((array)($data['handles'] ?? $block->getLayout()->getUpdate()->getHandles()));
$blockNames = $block->getChildNames();
?>
<script type="x-clientside-cache"><?= json_encode([$blockNames, $handles]) ?></script>

